alias c='clear'
alias i='ipython'
alias j='joshuto'
alias l='ls -ahltuF --color=auto'
alias t='tmux'
alias lg='lazygit'
alias sudo='sudo -E'
alias vim='nvim'
alias grep='grep --color'
alias paru='paru --bottomup'
alias noaslr='echo 0 | sudo tee /proc/sys/kernel/randomize_va_space'
alias glap="git log --all --graph --abbrev-commit --pretty=oneline"
