alias c='clear'
alias glap="git log --all --graph --abbrev-commit --pretty=oneline"
alias grep='grep --color'
alias i='ipython'
alias l='ls -ahltuF --color=auto'
alias lg='lazygit'
alias ls='ls --color=auto'
alias noaslr='echo 0 | sudo tee /proc/sys/kernel/randomize_va_space'
alias paru='paru --bottomup'
alias sudo='sudo -E'
alias t='tmux'
alias tt='sudo temp-throttle 70 | sudo tee /var/log/temp-throttle.log'
alias vim='nvim'
